# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '01153.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
import configparser
import cv2

class secondwindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 730)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 414, 730))
        self.label.setObjectName("label")
        self.label.setText("                                                 2 page")

        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 414, 730))
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("background-color: black")
        
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(80, 555, 120, 20))
        self.label_1.setObjectName("label_1")
        self.label_1.setStyleSheet("color: white;")
        self.label_1.setText("ID")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 608, 120, 20))
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setText("PW")
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 500, 120, 20))
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet("color: white;")
        
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 500, 100, 20))
        self.label_6.setObjectName("label_6")
        self.label_6.setStyleSheet("color: white;")
        
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 500, 100, 20))
        self.label_7.setObjectName("label_7")
        self.label_7.setStyleSheet("color: white;")
        
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 555, 200, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setStyleSheet("color: white; background-color: rgba(0, 0, 0, 0.0);")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 608, 200, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setStyleSheet("color: white; background-color: rgba(0, 0, 0, 0.0); ")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 680, 75, 20))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("color: black; background-color:")
        self.pushButton.setText("Button")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.lineEdit_2.returnPressed.connect(self.rejult)
        self.pushButton.pressed.connect(self.rejult)
        
        self.incorrect_attempts = 0
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.exit_application)
        self.remaining_seconds = 5

        
    def rejult(self):
        config = configparser.ConfigParser()
        config.read("login.ini")
        iid = config['user']['id']
        text = self.lineEdit.text()
        ppw = config['user']['pw']
        text2 = self.lineEdit_2.text()
        if text == iid and text2 == ppw :
            self.window = QtWidgets.QWidget()
            self.ui = secondwindow()
            self.ui.setupUi(self.window)
            self.window.show()
            MainWindow.hide()
                
        else:
            self.label_3.setHidden(False)
            self.label_6.setHidden(False)
            self.incorrect_attempts +=1
            self.label_3.setText("Error")     
            if self.incorrect_attempts < 6:
                self.label_6.setText(f'{self.incorrect_attempts}/5')
                self.label_6.setHidden(False)
                if self.incorrect_attempts == 5:
                    self.disable_input_fields()
                    self.timer.start(1000)
                
    def disable_input_fields(self):
        self.lineEdit.setDisabled(True)
        self.lineEdit_2.setDisabled(True)
        self.pushButton.setDisabled(True)
        self.label_3.setText("Wait for 30 seconds")
        self.label_6.setHidden(True)
        
    def enable_input_fields(self):
        self.label_3.setText("Enter it again")
        self.lineEdit.setEnabled(True)
        self.lineEdit_2.setEnabled(True)
        self.pushButton.setDisabled(True)
            
    
    def exit_application(self):
        self.remaining_seconds -= 1
        
        if self.remaining_seconds == 0:
            self.timer.stop()
            self.enable_input_fields()
            self.incorrect_attempts = 0
            self.remaining_seconds = 5
            self.label_6.setHidden(True)
                
           
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
