# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage, QPalette
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QPushButton, QListWidget, QMessageBox, QLineEdit, QTextEdit
from PyQt5.QtCore import QThread, pyqtSignal, Qt

from PyQt5.QtCore import QThread, pyqtSignal, Qt
from PyQt5.QtGui import QPixmap, QImage, QPalette
from PyQt5 import QtWidgets, QtCore, QtGui

import configparser
import time
import cv2
import os

from PyQt5.QtCore import QThread

gcount = 0
timecount = 0

class Ui_MainWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow    
        
        self.MainWindow.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.FramelessWindowHint)
        
        
        MainWindow.setObjectName("MainWindow") #if__name__main에서 상속받아서 앞으로는 MainWindow로 사용
        MainWindow.resize(1500, 844)
        self.centralwidget = QtWidgets.QWidget(MainWindow) #위젯 중앙을 설정을 하고 centralwidget에 MainWindow가 모두 넘겨줌(상속)
        self.centralwidget.setObjectName("centralwidget")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1500, 844))
        self.label_3.setObjectName("label_3")
        self.label_3.setPixmap(QtGui.QPixmap("cctv.jpg"))
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(355, 123, 527, 230))
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(932, 123, 527, 230))
        self.label_2.setObjectName("label_2")      
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(355, 405, 527, 230))
        self.label_4.setObjectName("label_2")   
        
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(932, 405, 527, 230))
        self.label_5.setObjectName("label_2")   
        
        self.th = Thread(self)
        self.th.changePixmap.connect(self.label.setPixmap)
        self.th.start()
        
        self.th2 = Thread2(self)
        self.th2.changePixmap.connect(self.label_2.setPixmap)
        self.th2.start()
        
        self.th3 = Thread3(self)
        self.th3.changePixmap.connect(self.label_4.setPixmap)
        self.th3.start()
        
        self.th4 = Thread4(self)
        self.th4.changePixmap.connect(self.label_5.setPixmap)
        self.th4.start()

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


class Thread(QThread):
    changePixmap = pyqtSignal(QPixmap)
    def __init__(self, parent=None):
        QThread.__init__(self, parent=parent)
        self.isRunning = True

    def run(self):
            image_files = "rtsp://210.99.70.120:1935/live/cctv001.stream"
            cap = cv2.VideoCapture(image_files)
            if cap.isOpened() is False:
                self.isRunning = False
            else :
                self.isRunning = True

            while self.isRunning:
                ret, frame = cap.read()
                rgbImage = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                convertToQtFormat = QImage(rgbImage.data, rgbImage.shape[1], rgbImage.shape[0], QImage.Format_RGB888)
                convertToQtFormat = QPixmap.fromImage(convertToQtFormat)
                p = convertToQtFormat.scaled(527, 230, Qt.IgnoreAspectRatio)
                self.changePixmap.emit(p)
                if not ret:
                    self.isRunning = False
                    break
            cap.release()
            cv2.destroyAllWindows()


    def resume(self):
        self.isRunning = True

    def stop(self):
        cv2.destroyAllWindows()
        self.isRunning = False
        
class Thread2(QThread):
    changePixmap = pyqtSignal(QPixmap)
    def __init__(self, parent=None):
        QThread.__init__(self, parent=parent)
        self.isRunning = True

    def run(self):
        image_files = "rtsp://210.99.70.120:1935/live/cctv002.stream"
        cap = cv2.VideoCapture(image_files)
        if cap.isOpened() is False:
            self.isRunning = False
        else :
            self.isRunning = True

        while self.isRunning:
            ret, frame = cap.read()
            rgbImage = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            convertToQtFormat = QImage(rgbImage.data, rgbImage.shape[1], rgbImage.shape[0], QImage.Format_RGB888)
            convertToQtFormat = QPixmap.fromImage(convertToQtFormat)
            p = convertToQtFormat.scaled(527, 230, Qt.IgnoreAspectRatio)
            self.changePixmap.emit(p)
            if not ret:
                self.isRunning = False
                break
        cap.release()
        cv2.destroyAllWindows()

    def resume(self):
        self.isRunning = True

    def stop(self):
        cv2.destroyAllWindows()
        self.isRunning = False
        
class Thread3(QThread):
    changePixmap = pyqtSignal(QPixmap)
    def __init__(self, parent=None):
        QThread.__init__(self, parent=parent)
        self.isRunning = True

    def run(self):
        image_files = "rtsp://210.99.70.120:1935/live/cctv003.stream"
        cap = cv2.VideoCapture(image_files)
        if cap.isOpened() is False:
            self.isRunning = False
        else :
            self.isRunning = True

        while self.isRunning:
            ret, frame = cap.read()
            rgbImage = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            convertToQtFormat = QImage(rgbImage.data, rgbImage.shape[1], rgbImage.shape[0], QImage.Format_RGB888)
            convertToQtFormat = QPixmap.fromImage(convertToQtFormat)
            p = convertToQtFormat.scaled(527, 230, Qt.IgnoreAspectRatio)
            self.changePixmap.emit(p)
            if not ret:
                self.isRunning = False
                break
        cap.release()
        cv2.destroyAllWindows()

    def resume(self):
        self.isRunning = True

    def stop(self):
        cv2.destroyAllWindows()
        self.isRunning = False
        
class Thread4(QThread):
    changePixmap = pyqtSignal(QPixmap)
    def __init__(self, parent=None):
        QThread.__init__(self, parent=parent)
        self.isRunning = True

    def run(self):
        image_files = "rtsp://210.99.70.120:1935/live/cctv004.stream"
        cap = cv2.VideoCapture(image_files)
        if cap.isOpened() is False:
            self.isRunning = False
        else :
            self.isRunning = True

        while self.isRunning:
            ret, frame = cap.read()
            rgbImage = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            convertToQtFormat = QImage(rgbImage.data, rgbImage.shape[1], rgbImage.shape[0], QImage.Format_RGB888)
            convertToQtFormat = QPixmap.fromImage(convertToQtFormat)
            p = convertToQtFormat.scaled(527, 230, Qt.IgnoreAspectRatio)
            self.changePixmap.emit(p)
            if not ret:
                self.isRunning = False
                break
        cap.release()
        cv2.destroyAllWindows()

    def resume(self):
        self.isRunning = True

    def stop(self):
        cv2.destroyAllWindows()
        self.isRunning = False
        
if __name__ == "__main__":
    import sys #object는 윈도의 최고 조상
    app = QtWidgets.QApplication(sys.argv) # sys.argv는 현재 작업중인.py 절대 경로를 인자로 넘겨줌
    MainWindow = QtWidgets.QMainWindow() #윈도우 UI를 연결하기 위한 상속
    ui = Ui_MainWindow() #위 클래스를 ui 변수에 넣는다 여기서 부터 클래스 개념 필요
    ui.setupUi(MainWindow) #위 QtWidgets.QMainWindows()에서 상속받아서 위 SetupUi함수 인자로 넘겨줌 즉 위젯 실행하라는 뜻
    MainWindow.show() #MainWindow를 화면에 표시
    sys.exit(app.exec_()) #무한루프


