# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
import configparser
import cv2
import os

stop = 0
imstop = 0
rtspstop = 0

class secondwindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
                
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 150, 400, 400))
        self.label_4.setObjectName("label")
       
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 640, 131, 21))
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 700, 700))
        self.label_4.setStyleSheet("background-color: rgb(67, 67, 67);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(400, 500, 80, 21)
        self.btn.setObjectName("PushButton")
        self.btn.setText("Movie")
        self.btn.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(67, 67, 67);")
        self.btn.clicked.connect(self.ishow) 
        
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(400, 530, 80, 21)
        self.btn3.setObjectName("PushButton3")
        self.btn3.setText("STOP")
        self.btn3.setStyleSheet("color: rgb(255, 255, 255);background-color: red;")
        self.btn3.clicked.connect(self.moviestop)
        
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(500, 500, 80, 21)
        self.btn1.setObjectName("PushButton1")
        self.btn1.setText("Image")
        self.btn1.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(67, 67, 67);")
        self.btn1.clicked.connect(self.ishow1)
        
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(500, 530, 80, 21)
        self.btn4.setObjectName("PushButton4")
        self.btn4.setText("ImageStop")
        self.btn4.setStyleSheet("background-color: yellow;")
        self.btn4.clicked.connect(self.imstop)        
        
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(600, 500, 80, 21)
        self.btn2.setObjectName("PushButton2")
        self.btn2.setText("RTSP")
        self.btn2.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(67, 67, 67);")
        self.btn2.clicked.connect(self.ishow2) 
        
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(600, 530, 80, 21)
        self.btn5.setObjectName("PushButton5")
        self.btn5.setText("RTSPSTOP")
        self.btn5.setStyleSheet("color: rgb(255, 255, 255);background-color: green;")
        self.btn5.clicked.connect(self.rtspstop) 
        
    
    def moviestop(self):
        global stop 
        stop = 1
        
    def imstop(self):
        global imstop 
        imstop = 1
        
    def rtspstop(self):
        global rtspstop
        rtspstop = 1
        
    def ishow(self):
        global stop
        #print("show완료")
        image_files = "C:\\Study\\20240131\\20240130\\team_2.mp4"       
        cap = cv2.VideoCapture(image_files)          
        while True:  
            print(stop)
            ret, img = cap.read()       
            if ret:
                cv2.imshow(image_files, img)
                cv2.waitKey(33)
                if stop == 1:
                    cap.release()
                    cv2.destroyAllWindows()
                    stop = 0
                    return
            else :
                cap.release()
                cv2.destroyAllWindows()
                return
        
    def ishow1(self):
        global imstop
        print("11111show완료")        
        filelist = os.listdir("C:\\Study\\backup\\")     
        print(filelist)
        while True:
            for i in filelist:                       
                if i.endswith(".png"):
                    image = cv2.imread("C:\\Study\\backup\\" + str(i), cv2.IMREAD_COLOR)
                    image2 = cv2.resize(image, (400,400))
                    cv2.imshow('AI', image2)  
                    cv2.waitKey(1000)
                    if imstop == 1:
                        cv2.destroyAllWindows()
                        imstop = 0
                        break
                        return
            cv2.destroyAllWindows()
            break                        
        
    def ishow2(self):
        global rtspstop 
        print("22222show완료")
        image_files = "rtsp://210.99.70.120:1935/live/cctv001.stream"        
        cap = cv2.VideoCapture(image_files)                   
        while True:            
            ret, img = cap.read()            
            cv2.imshow("a", img)            
            cv2.waitKey(33)
            if rtspstop == 1:
                cap.release()
                cv2.destroyAllWindows()
                rtspstop = 0
                break
                return     

        cap.release()
        cv2.destroyAllWindows()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        ######################################################################
        
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(270, 140, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        
        ######################################################################
        
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 180, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.returnPressed.connect(self.open)
        
        ######################################################################
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 150, 56, 12))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        
        ######################################################################
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 190, 56, 12))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        
        ######################################################################
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 220, 181, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        
        ######################################################################
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 811, 601))
        self.label_4.setStyleSheet("background-color: rgb(67, 67, 67);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        
        ######################################################################
        
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()            
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def open(self):        
        text = self.lineEdit.text()
        text2 = self.lineEdit_2.text()
        config = configparser.ConfigParser()
        config.read("ai.ini")
        pid = config['user']['id']
        ppw = config['user']['pw']
        
        if text == pid and text2 == ppw:
            self.label_3.setText("FirstClick")  
            self.label_4.setStyleSheet("background-color: red;")     
            self.window = QtWidgets.QWidget()
            self.ui = secondwindow()
            self.ui.setupUi(self.window)
            self.window.show()
            MainWindow.hide()
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "PW"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
