# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '01153.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
import configparser
import time
import random 

timecount = 0

class secondwindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(70, 60, 272, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 414, 730))
        self.label_4.setObjectName("label_4")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 650, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("Choose")
        self.pushButton.pressed.connect(self.random)
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 650, 75, 23))
        self.pushButton_2.setObjectName("pushButton")
        self.pushButton_2.setText("Choose")
        self.pushButton_2.pressed.connect(self.random)
        
    def show1(self):
        self.label_4.setPixmap(QtGui.QPixmap("1.jpg"))
        self.calendarWidget.setHidden(True)
        self.pushButton.setHidden(True)
        self.pushButton_2.setHidden(True)
       
    def show2(self):
        self.label_4.setPixmap(QtGui.QPixmap("2.jpg"))
        self.calendarWidget.setHidden(True)
        self.pushButton.setHidden(True)
        self.pushButton_2.setHidden(True)
        
    def random(self):
        a = random.randrange(0,2)
        if a == 1:
            self.label_4.setPixmap(QtGui.QPixmap("2.jpg"))
        else:
            self.label_4.setPixmap(QtGui.QPixmap("1.jpg"))
        self.calendarWidget.setHidden(True)
        self.calendarWidget.setHidden(True)
        self.pushButton.setHidden(True)
        self.pushButton_2.setHidden(True)
        
    

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 516, 730))
        self.label_4.setObjectName("label_4")
        self.label_4.setPixmap(QtGui.QPixmap("lock.jpg"))
        
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 516, 730))
        self.label_5.setObjectName("label_5")
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 500, 120, 20))
        self.label_3.setObjectName("label_3")
        
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 500, 100, 20))
        self.label_6.setObjectName("label_6")
        
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 500, 100, 20))
        self.label_7.setObjectName("label_7")
        
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 540, 170, 30))
        self.lineEdit.setObjectName("lineEdit")
        
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 600, 170, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 650, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("Check")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.lineEdit_2.returnPressed.connect(self.rejult)
        self.pushButton.pressed.connect(self.rejult)
        
        self.incorrect_attempts = 0
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.exit_application)
        self.remaining_seconds = 5

        
    def rejult(self):
        config = configparser.ConfigParser()
        config.read("test.ini")
        iid = config['user']['id']
        text = self.lineEdit.text()
        ppw = config['user']['pw']
        text2 = self.lineEdit_2.text()
        if text == iid and text2 == ppw :
            self.window = QtWidgets.QWidget()
            self.ui = secondwindow()
            self.ui.setupUi(self.window)
            self.window.show()
            MainWindow.hide()
                
        else:
            self.label_3.setHidden(False)
            self.label_6.setHidden(False)
            self.incorrect_attempts +=1
            self.label_3.setText("틀렸습니다")     
            if self.incorrect_attempts < 6:
                self.label_6.setText(f'{self.incorrect_attempts}/5')
                self.label_6.setHidden(False)
                if self.incorrect_attempts == 5:
                    self.disable_input_fields()
                    self.timer.start(1000)


                
    def disable_input_fields(self):
        # self.label_3.setHidden(True)
        # self.label_6.setHidden(True)
        self.lineEdit.setDisabled(True)
        self.lineEdit_2.setDisabled(True)
        self.pushButton.setDisabled(True)
        self.label_3.setText("30초 후에 가능합니다")
        self.label_6.setHidden(True)
        
    def enable_input_fields(self):
        self.label_3.setText("다시 입력하세요")
        self.lineEdit.setEnabled(True)
        self.lineEdit_2.setEnabled(True)
        self.pushButton.setEnabled(True)
            
    # def delay(self):
    #     for i in range(4):
    #         time.sleep(1)
    #         self.label_6.setText("다시 입력하시오")   
    #         self.label_7.setText("")
    
    def exit_application(self):
        self.remaining_seconds -= 1
        
        if self.remaining_seconds == 0:
            # When the countdown reaches 0, stop the timer and exit the application
            self.timer.stop()
            self.enable_input_fields()
            self.incorrect_attempts = 0
            self.remaining_seconds = 5
            # self.label_3.setHidden(True)
            self.label_6.setHidden(True)
                
           
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
