# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '01153.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
import configparser
import cv2


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 730)
    
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 414, 730))
        self.label.setObjectName("label")
        self.label.setStyleSheet("background-color: black")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 600, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("color: black; background-color: white;")
        self.pushButton.setText("Play")
        self.pushButton.pressed.connect(self.open)
        
    def open(self):
        image_files = ['C:\\study\\20240117\\coffee.mp4']
        for image_file in image_files:
            cap = cv2.VideoCapture(image_file)
            if cap.isOpened():
                while True:
                    ret, img = cap.read() # ret: 영상이 끊겼는지 아닌지 확인 img: 이미지 + 코덱
                    if ret: # 영상이 값이 있다면 아래를 실행
                        cv2.imshow(image_file, img)
                        if cv2.waitKey(1000) == 27:
                            break
                        if cv2.getWindowProperty(image_file, cv2.WND_PROP_VISIBLE) < 1:
                            break
                    else:
                        cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
                        
            else:
                print('can not') 
                             

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())