# Generated by Django 4.0.1 on 2024-04-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mem_pass', models.CharField(max_length=15)),
                ('mem_name', models.CharField(max_length=10)),
                ('mem_add1', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
